package com.example.examplemod.mixin;

import com.example.examplemod.ExampleMod;
import com.example.examplemod.common.config.ModCommonConfig;
import com.example.examplemod.common.util.TickUtils;
import net.minecraft.world.entity.player.Player;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Minimal mixin example - delete it if you do not modify vanilla behaviour.
 *
 * <p>How the naming works on 1.20.1: mods are written against official (Mojang) names, but the game
 * runs SRG names, so {@code "tick"} has to be rewritten to {@code m_8119_} at build time. That is
 * what the refmap generated by the {@code mixin {}} block in {@code build.gradle} does, and why the
 * {@code <modid>.mixins.json} here has no {@code refmap} field - Gradle injects it. Removing that
 * block (or forgetting {@code MixinConfigs} in the jar manifest) leaves you with mixins that fail
 * to apply at runtime with no obvious cause.</p>
 *
 * <p>Prefer Access Transformers over mixins whenever you only need to widen visibility, and keep
 * each feature in its own mixin config once you have more than a handful of mixins so users and
 * other mods can turn them off individually.</p>
 */
@Mixin(Player.class)
public class PlayerTickMixin {
    private static final int LOG_INTERVAL = TickUtils.secondsToTicks(30);

    @Inject(method = "tick", at = @At("HEAD"))
    private void examplemod$logTickDemo(CallbackInfo ci) {
        Player self = (Player) (Object) this;
        if (ModCommonConfig.logPlayerTickDemo && self.tickCount % LOG_INTERVAL == 0) {
            ExampleMod.LOGGER.info("[{}] tick demo: {} at {}",
                    ExampleMod.MODID, self.getName().getString(), self.blockPosition());
        }
    }
}
